/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DaftarProdukRouteImport } from './routes/daftar-produk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as KategoriIndexRouteImport } from './routes/kategori/index'
import { Route as ProdukSlugRouteImport } from './routes/produk/$slug'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as KategoriSlugRouteImport } from './routes/kategori/$slug'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarProdukRoute = DaftarProdukRouteImport.update({
  id: '/daftar-produk',
  path: '/daftar-produk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriIndexRoute = KategoriIndexRouteImport.update({
  id: '/kategori/',
  path: '/kategori/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar-produk': typeof DaftarProdukRoute
  '/dashboard': typeof DashboardRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/kategori/': typeof KategoriIndexRoute
  '/news/': typeof NewsIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar-produk': typeof DaftarProdukRoute
  '/dashboard': typeof DashboardRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/kategori': typeof KategoriIndexRoute
  '/news': typeof NewsIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftar-produk': typeof DaftarProdukRoute
  '/dashboard': typeof DashboardRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/kategori/': typeof KategoriIndexRoute
  '/news/': typeof NewsIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar-produk'
    | '/dashboard'
    | '/kontak'
    | '/layanan'
    | '/login'
    | '/tentang'
    | '/kategori/$slug'
    | '/news/$slug'
    | '/produk/$slug'
    | '/kategori/'
    | '/news/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar-produk'
    | '/dashboard'
    | '/kontak'
    | '/layanan'
    | '/login'
    | '/tentang'
    | '/kategori/$slug'
    | '/news/$slug'
    | '/produk/$slug'
    | '/kategori'
    | '/news'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/daftar-produk'
    | '/dashboard'
    | '/kontak'
    | '/layanan'
    | '/login'
    | '/tentang'
    | '/kategori/$slug'
    | '/news/$slug'
    | '/produk/$slug'
    | '/kategori/'
    | '/news/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarProdukRoute: typeof DaftarProdukRoute
  DashboardRoute: typeof DashboardRoute
  KontakRoute: typeof KontakRoute
  LayananRoute: typeof LayananRoute
  LoginRoute: typeof LoginRoute
  TentangRoute: typeof TentangRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  KategoriIndexRoute: typeof KategoriIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-produk': {
      id: '/daftar-produk'
      path: '/daftar-produk'
      fullPath: '/daftar-produk'
      preLoaderRoute: typeof DaftarProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/': {
      id: '/kategori/'
      path: '/kategori'
      fullPath: '/kategori/'
      preLoaderRoute: typeof KategoriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarProdukRoute: DaftarProdukRoute,
  DashboardRoute: DashboardRoute,
  KontakRoute: KontakRoute,
  LayananRoute: LayananRoute,
  LoginRoute: LoginRoute,
  TentangRoute: TentangRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  KategoriIndexRoute: KategoriIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
